apiVersion: v1
kine: ConfigMap
metadata:
  name: global-config-map
data:
  # Global
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: https://+:443;http://+:80
  ASPNETCORE_Kestrel__Certificates__Default__Password: Domic123!@#
  ASPNETCORE_Kestrel__Certificates__Default__Path: /https/Domic.WebAPI.pfx
  E-RabbitMQ-Host: domic.rabbit.mq
  E-RabbitMQ-Port: 5672
  E-RabbitMQ-Username: domic
  E-RabbitMQ-Password: Domic123!@#
  E-RedisConnectionString: 
  Elastic-Username: domic
  Elastic-Password: Domic123!@#
  Elastic-Host: http://domic.elastic.search:9200

  # AggregateArticleService
  Aggregate-Article-Elastic-Index: aggregatearticle
  Aggregate-Article-RedisConnectionString: domic.aggregate.redis:6379
  Aggregate-Article-SqlServerConnectionString: Server=domic.aggregate.article.query.sql.server,1433;Database=AggregateArticleService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Integrated Security=false;
  Aggregate-Article-Host: domic.aggregate.article.api
  Aggregate-Article-Port: 443

  # AggregateTermService
  Aggregate-Term-Elastic-Index: aggregateterm
  Aggregate-Term-RedisConnectionString: domic.aggregateterm.redis:6379
  Aggregate-Term-SqlServerConnectionString: Server=domic.aggregate.term.query.sql.server,1433;Database=AggregateTermService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Integrated Security=false;
  Aggregate-Term-Host: domic.aggregate.term.api
  Aggregate-Term-Port: 443

  # AggregateTicketService
  Aggregate-Ticket-Elastic-Index: aggregateticket
  Aggregate-Ticket-RedisConnectionString: domic.aggregateticket.redis:6379
  Aggregate-Ticket-SqlServerConnectionString: Server=domic.aggregate.ticket.command.sql.server,1433;Database=AggregateTicketService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Integrated Security=false;
  Aggregate-Ticket-Host: domic.aggregate.ticket.api
  Aggregate-Ticket-Port: 443

  # Article
  Article-Elastic-Index: article
  Article-RedisConnectionString: domic.article.redis:6379
  Article-SqlServerConnectionString: Server=domic.article.sql.server,1433;Database=ArticleService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Integrated Security=false;
  Article-Host: domic.article.api
  Article-Port: 443

  # Comment
  Comment-Elastic-Index: comment
  Comment-RedisConnectionString: domic.comment.redis:6379
  Comment-SqlServerConnectionString: Server=domic.comment.sql.server,1433;Database=CommentService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Integrated Security=false;
  Comment-Host: domic.article.api
  Comment-Port: 443

  # Financial
  Comment-Elastic-Index: financial
  Comment-RedisConnectionString: domic.financial.redis:6379
  Comment-SqlServerConnectionString: Server=domic.financial.sql.server,1433;Database=FinancialService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Integrated Security=false;
  Comment-Host: domic.financial.api
  Comment-Port: 443

  # Identity
  Comment-Elastic-Index: identity
  Comment-RedisConnectionString: domic.identity.redis:6379
  Comment-SqlServerConnectionString: Server=domic.identity.sql.server,1433;Database=IdentityService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Integrated Security=false;
  Comment-Host: domic.identity.api
  Comment-Port: 443

  # User
  User-Elastic-Index: user
  User-I-RabbitMQ-Host:
  User-I-RabbitMQ-Port:
  User-I-RabbitMQ-Username:
  User-I-RabbitMQ-Password:
  User-I-RedisConnectionString: domic.identity.redis:6379
  User-Q-SqlServerConnectionString: Server=domic.identity.sql.server,1433;Database=IdentityService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Integrated Security=false;
  User-C-SqlServerConnectionString: Server=domic.identity.sql.server,1433;Database=IdentityService;User ID=sa;Password=Domic123!@#;MultipleActiveResultSets=true;Integrated Security=false;
  User-Host: domic.identity.api
  User-Port: 443